# Generated by Django 4.2.7 on 2023-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
